api_hash: 2593617fafbd5ca3ad3ccb7d5004bd8d
api_id: 27415009
bot_token: 7272640684:AAErc5g2ygJpkWGEb01_wO3goOhi-O4ziNw
web_host: 192.168.196.90
#chat:
#- chat_id: 7272640684:AAErc5g2ygJpkWGEb01
#  last_read_message_id: 0
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
disable_syslog: []
save_path: /app/downloads
language: ZH
max_download_task: 30
