api_hash: 2593617fafbd5ca3ad3ccb7d5004bd8d
api_id: 27415009
chat:
- chat_id: 7272640684:AAErc5g2ygJpkWGEb01
  last_read_message_id: 0
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
max_download_task: 30
